name = "TestPackage4"
uuid = "606b36d0-56dd-4805-8383-5f607c1f4394"
authors = ["Walter Levy <klwlevy@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
